// FEATURE: F1
// FEATURE: F3

use std::error::Error;
use std::fmt;

#[cfg(test)]
use crate::crds::federation::FederationConnection;
use crate::crds::federation::{FederationSpec, FederationSpecError, FederationType};

/// Foreign data wrapper extension installed for an FDW-backed federation
/// target. The reconcile plan installs exactly one of these per
/// `FederationSpec`.
pub const MYSQL_FDW_EXTENSION: &str = "mysql_fdw";
pub const MONGO_FDW_EXTENSION: &str = "mongo_fdw";
pub const ORACLE_FDW_EXTENSION: &str = "oracle_fdw";
pub const TDS_FDW_EXTENSION: &str = "tds_fdw";

/// Foreign-table name suffix used when the reconciler installs the
/// per-federation guard table that tracks foreign-table provenance.
pub const FEDERATION_PROVENANCE_TABLE: &str = "ai_blaise_federation_provenance";

/// Metadata tables owned by the reconciler apply plan. These tables are kept
/// outside the sidecar runtime so the SQL plan can be applied idempotently by
/// an operator job, a smoke harness, or a future controller executor.
pub const FEDERATION_METADATA_TABLES_SQL: &str = r#"CREATE TABLE IF NOT EXISTS ai_blaise_federation_provenance (
    federation_name text PRIMARY KEY,
    federation_type text NOT NULL,
    server_name text NOT NULL,
    foreign_schema_prefix text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS ai_blaise_iceberg_federation (
    server_name text PRIMARY KEY,
    secret_ref text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);"#;

/// SQL apply step generated by the federation reconciler.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct FederationApplyStep {
    pub name: String,
    pub feature_id: &'static str,
    pub sql: String,
    pub idempotent: bool,
}

impl FederationApplyStep {
    fn new(
        name: impl Into<String>,
        feature_id: &'static str,
        sql: impl Into<String>,
        idempotent: bool,
    ) -> Self {
        Self {
            name: name.into(),
            feature_id,
            sql: sql.into(),
            idempotent,
        }
    }
}

/// Apply plan composed of `FederationApplyStep`s in execution order.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct FederationApplyPlan {
    pub steps: Vec<FederationApplyStep>,
}

impl FederationApplyPlan {
    pub fn sql_script(&self) -> String {
        self.steps
            .iter()
            .map(|step| step.sql.trim_end())
            .collect::<Vec<_>>()
            .join("\n")
    }
}

/// Server-side identity for the federation target. The plan picks between an
/// FDW-backed server (`oracle_fdw`, `mysql_fdw`, etc.) and an analytical
/// (Iceberg) bridge for warehouse-class targets so the operator owns the
/// routing decision instead of leaking it into companion SQL.
#[derive(Debug, Clone, Eq, PartialEq)]
pub enum FederationBackend {
    Fdw { extension: &'static str },
    AnalyticalIceberg,
}

impl FederationBackend {
    pub fn from_type(federation_type: FederationType) -> Self {
        match federation_type {
            FederationType::MySql => Self::Fdw {
                extension: MYSQL_FDW_EXTENSION,
            },
            FederationType::Mongo => Self::Fdw {
                extension: MONGO_FDW_EXTENSION,
            },
            FederationType::Oracle => Self::Fdw {
                extension: ORACLE_FDW_EXTENSION,
            },
            // TDS FDW covers Microsoft SQL Server style targets; the
            // analytical CRD's Databricks slot would route through Iceberg
            // instead. Snowflake / BigQuery / Databricks all reach Postgres
            // through the Iceberg federation bridge owned by sidecar/analytical.
            FederationType::Snowflake | FederationType::BigQuery | FederationType::Databricks => {
                Self::AnalyticalIceberg
            }
        }
    }

    /// Returns the FDW extension name if this backend is FDW-backed.
    pub fn fdw_extension(&self) -> Option<&'static str> {
        match self {
            Self::Fdw { extension } => Some(extension),
            Self::AnalyticalIceberg => None,
        }
    }

    pub fn is_iceberg(&self) -> bool {
        matches!(self, Self::AnalyticalIceberg)
    }
}

/// Resolved reconcile plan derived from a `FederationSpec`. The plan exposes
/// the FDW extension to install (if any), the server/user-mapping identity
/// derived from `connection.secret_ref`, and the apply step list that the
/// operator runtime executes to bring the foreign schema to the desired state.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct FederationReconcilePlan {
    pub federation_name: String,
    pub federation_type: FederationType,
    pub backend: FederationBackend,
    pub server_name: String,
    pub foreign_schema_prefix: String,
    pub secret_ref: String,
}

impl TryFrom<&FederationSpec> for FederationReconcilePlan {
    type Error = FederationReconcileError;

    fn try_from(spec: &FederationSpec) -> Result<Self, Self::Error> {
        spec.validate()?;

        let backend = FederationBackend::from_type(spec.federation_type);

        Ok(Self {
            federation_name: spec.name.clone(),
            federation_type: spec.federation_type,
            backend,
            server_name: derive_server_name(&spec.name),
            foreign_schema_prefix: spec.foreign_schema_prefix.clone(),
            secret_ref: spec.connection.secret_ref.clone(),
        })
    }
}

impl FederationReconcilePlan {
    /// Returns the apply plan that creates the FDW extension, server, user
    /// mapping, and provenance schema. The list is deterministic so the
    /// operator runtime can diff steps across reconciles.
    pub fn apply_plan(&self) -> FederationApplyPlan {
        let mut steps = vec![FederationApplyStep::new(
            "ensure_federation_metadata_tables",
            "F1",
            FEDERATION_METADATA_TABLES_SQL,
            true,
        )];

        match &self.backend {
            FederationBackend::Fdw { extension } => {
                steps.push(FederationApplyStep::new(
                    "ensure_fdw_extension",
                    "F1",
                    format!("CREATE EXTENSION IF NOT EXISTS {extension};"),
                    true,
                ));
                steps.push(FederationApplyStep::new(
                    "ensure_foreign_server",
                    "F1",
                    create_server_sql(&self.server_name, extension, &self.secret_ref),
                    true,
                ));
                steps.push(FederationApplyStep::new(
                    "ensure_user_mapping",
                    "F1",
                    create_user_mapping_sql(&self.server_name, &self.secret_ref),
                    true,
                ));
            }
            FederationBackend::AnalyticalIceberg => {
                steps.push(FederationApplyStep::new(
                    "ensure_iceberg_federation_bridge",
                    "F3",
                    ensure_iceberg_bridge_sql(&self.server_name, &self.secret_ref),
                    true,
                ));
            }
        }

        steps.push(FederationApplyStep::new(
            "ensure_foreign_schema_namespace",
            "F1",
            ensure_namespace_sql(&self.foreign_schema_prefix),
            true,
        ));
        steps.push(FederationApplyStep::new(
            "record_federation_provenance",
            "F1",
            record_provenance_sql(self),
            true,
        ));

        FederationApplyPlan { steps }
    }

    pub fn apply_sql_script(&self) -> String {
        self.apply_plan().sql_script()
    }

    /// Render the teardown plan executed on Federation deletion. The plan
    /// drops the foreign server (which cascades through CREATE FOREIGN TABLE
    /// children only when `RESTRICT` is replaced with `CASCADE`; the
    /// operator runtime warns when dependent objects exist).
    pub fn teardown_sql_script(&self) -> String {
        let mut commands = Vec::new();
        commands.push(format!(
            "DELETE FROM {table} WHERE federation_name = {name};",
            table = FEDERATION_PROVENANCE_TABLE,
            name = sql_literal(&self.federation_name)
        ));
        if matches!(self.backend, FederationBackend::Fdw { .. }) {
            commands.push(format!(
                "DROP SERVER IF EXISTS {server} RESTRICT;",
                server = quote_identifier(&self.server_name)
            ));
        } else {
            commands.push(format!(
                "DELETE FROM ai_blaise_iceberg_federation WHERE server_name = {server};",
                server = sql_literal(&self.server_name)
            ));
        }
        commands.join("\n")
    }
}

fn derive_server_name(federation_name: &str) -> String {
    format!(
        "ai_blaise_federation_{}",
        sanitize_identifier(federation_name)
    )
}

fn sanitize_identifier(raw: &str) -> String {
    raw.trim()
        .chars()
        .map(|character| match character {
            'A'..='Z' => character.to_ascii_lowercase(),
            'a'..='z' | '0'..='9' | '_' => character,
            _ => '_',
        })
        .collect::<String>()
        .trim_matches('_')
        .to_string()
}

fn create_server_sql(server: &str, extension: &str, secret_ref: &str) -> String {
    format!(
        "DO $ai_blaise_federation$\nBEGIN\n    IF NOT EXISTS (SELECT 1 FROM pg_foreign_server WHERE srvname = {server_literal}) THEN\n        EXECUTE format('CREATE SERVER %I FOREIGN DATA WRAPPER %I OPTIONS (secret_ref %L)', {server_literal}, {extension_literal}, {secret_literal});\n    END IF;\nEND\n$ai_blaise_federation$;",
        server_literal = sql_literal(server),
        extension_literal = sql_literal(extension),
        secret_literal = sql_literal(secret_ref),
    )
}

fn create_user_mapping_sql(server: &str, secret_ref: &str) -> String {
    format!(
        "DO $ai_blaise_federation$\nBEGIN\n    IF NOT EXISTS (\n        SELECT 1 FROM pg_user_mappings WHERE srvname = {server_literal} AND usename = current_user\n    ) THEN\n        EXECUTE format('CREATE USER MAPPING FOR CURRENT_USER SERVER %I OPTIONS (secret_ref %L)', {server_literal}, {secret_literal});\n    ELSE\n        EXECUTE format('ALTER USER MAPPING FOR CURRENT_USER SERVER %I OPTIONS (SET secret_ref %L)', {server_literal}, {secret_literal});\n    END IF;\nEND\n$ai_blaise_federation$;",
        server_literal = sql_literal(server),
        secret_literal = sql_literal(secret_ref),
    )
}

fn ensure_iceberg_bridge_sql(server: &str, secret_ref: &str) -> String {
    format!(
        "INSERT INTO ai_blaise_iceberg_federation (server_name, secret_ref) VALUES ({server}, {secret}) ON CONFLICT (server_name) DO UPDATE SET secret_ref = EXCLUDED.secret_ref;",
        server = sql_literal(server),
        secret = sql_literal(secret_ref),
    )
}

fn ensure_namespace_sql(foreign_schema_prefix: &str) -> String {
    format!(
        "CREATE SCHEMA IF NOT EXISTS {schema};",
        schema = quote_identifier(foreign_schema_prefix)
    )
}

fn record_provenance_sql(plan: &FederationReconcilePlan) -> String {
    format!(
        "INSERT INTO {table} (federation_name, federation_type, server_name, foreign_schema_prefix) VALUES ({name}, {ftype}, {server}, {schema}) ON CONFLICT (federation_name) DO UPDATE SET server_name = EXCLUDED.server_name, foreign_schema_prefix = EXCLUDED.foreign_schema_prefix, federation_type = EXCLUDED.federation_type;",
        table = FEDERATION_PROVENANCE_TABLE,
        name = sql_literal(&plan.federation_name),
        ftype = sql_literal(federation_type_label(plan.federation_type)),
        server = sql_literal(&plan.server_name),
        schema = sql_literal(&plan.foreign_schema_prefix),
    )
}

fn federation_type_label(federation_type: FederationType) -> &'static str {
    match federation_type {
        FederationType::Snowflake => "snowflake",
        FederationType::BigQuery => "bigquery",
        FederationType::Databricks => "databricks",
        FederationType::MySql => "mysql",
        FederationType::Mongo => "mongo",
        FederationType::Oracle => "oracle",
    }
}

fn sql_literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn quote_identifier(value: &str) -> String {
    format!("\"{}\"", value.replace('"', "\"\""))
}

#[derive(Debug, Clone, Eq, PartialEq)]
pub enum FederationReconcileError {
    InvalidSpec(FederationSpecError),
}

impl fmt::Display for FederationReconcileError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidSpec(error) => write!(formatter, "{error}"),
        }
    }
}

impl Error for FederationReconcileError {}

impl From<FederationSpecError> for FederationReconcileError {
    fn from(error: FederationSpecError) -> Self {
        Self::InvalidSpec(error)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn snowflake_spec() -> FederationSpec {
        FederationSpec {
            name: "warehouse".to_string(),
            federation_type: FederationType::Snowflake,
            connection: FederationConnection {
                secret_ref: "snowflake-warehouse".to_string(),
            },
            foreign_schema_prefix: "snowflake_raw".to_string(),
        }
    }

    fn mysql_spec() -> FederationSpec {
        FederationSpec {
            name: "legacy-orders".to_string(),
            federation_type: FederationType::MySql,
            connection: FederationConnection {
                secret_ref: "mysql-orders".to_string(),
            },
            foreign_schema_prefix: "orders_legacy".to_string(),
        }
    }

    #[test]
    fn snowflake_routes_through_iceberg_bridge() {
        let plan = FederationReconcilePlan::try_from(&snowflake_spec()).expect("valid plan");

        assert!(plan.backend.is_iceberg());
        assert_eq!(plan.server_name, "ai_blaise_federation_warehouse");

        let apply_plan = plan.apply_plan();
        let names: Vec<&str> = apply_plan
            .steps
            .iter()
            .map(|step| step.name.as_str())
            .collect();
        assert_eq!(
            names,
            vec![
                "ensure_federation_metadata_tables",
                "ensure_iceberg_federation_bridge",
                "ensure_foreign_schema_namespace",
                "record_federation_provenance",
            ]
        );

        let script = plan.apply_sql_script();
        assert!(script.contains("ai_blaise_iceberg_federation"));
        assert!(script.contains("CREATE TABLE IF NOT EXISTS ai_blaise_federation_provenance"));
        assert!(script.contains("snowflake-warehouse"));
        assert!(script.contains("CREATE SCHEMA IF NOT EXISTS \"snowflake_raw\""));
        assert!(script.contains("'snowflake'"));
    }

    #[test]
    fn mysql_installs_fdw_extension_and_server() {
        let plan = FederationReconcilePlan::try_from(&mysql_spec()).expect("valid plan");

        assert_eq!(plan.backend.fdw_extension(), Some(MYSQL_FDW_EXTENSION));
        assert_eq!(plan.server_name, "ai_blaise_federation_legacy_orders");

        let apply_plan = plan.apply_plan();
        let names: Vec<&str> = apply_plan
            .steps
            .iter()
            .map(|step| step.name.as_str())
            .collect();
        assert_eq!(
            names,
            vec![
                "ensure_federation_metadata_tables",
                "ensure_fdw_extension",
                "ensure_foreign_server",
                "ensure_user_mapping",
                "ensure_foreign_schema_namespace",
                "record_federation_provenance",
            ]
        );

        let script = plan.apply_sql_script();
        assert!(script.contains("CREATE EXTENSION IF NOT EXISTS mysql_fdw;"));
        assert!(script.contains("CREATE SERVER"));
        assert!(script.contains("CREATE USER MAPPING"));
        assert!(script.contains("ALTER USER MAPPING"));
        assert!(script.contains("'mysql'"));
    }

    #[test]
    fn teardown_warns_via_restrict_for_fdw_servers() {
        let plan = FederationReconcilePlan::try_from(&mysql_spec()).expect("valid plan");
        let teardown = plan.teardown_sql_script();
        assert!(teardown.contains("DROP SERVER IF EXISTS"));
        assert!(teardown.contains("RESTRICT"));
        assert!(teardown.contains(FEDERATION_PROVENANCE_TABLE));
    }

    #[test]
    fn teardown_iceberg_removes_bridge_row_without_drop_server() {
        let plan = FederationReconcilePlan::try_from(&snowflake_spec()).expect("valid plan");
        let teardown = plan.teardown_sql_script();
        assert!(!teardown.contains("DROP SERVER"));
        assert!(teardown.contains("ai_blaise_iceberg_federation"));
        assert!(teardown.contains("ai_blaise_federation_warehouse"));
    }

    #[test]
    fn invalid_spec_propagates_validation_error() {
        let mut spec = mysql_spec();
        spec.connection.secret_ref = String::new();
        assert_eq!(
            FederationReconcilePlan::try_from(&spec),
            Err(FederationReconcileError::InvalidSpec(
                FederationSpecError::MissingRequiredField("connection.secret_ref")
            ))
        );
    }

    #[test]
    fn server_name_sanitizes_non_identifier_characters() {
        let mut spec = mysql_spec();
        spec.name = "Legacy Orders!".to_string();
        let plan = FederationReconcilePlan::try_from(&spec).expect("valid plan");
        assert_eq!(plan.server_name, "ai_blaise_federation_legacy_orders");
    }
}
