// FEATURE: EF3

use std::error::Error;
use std::fmt;

use crate::crds::function::{
    FunctionEvent, FunctionRuntime, FunctionSource, FunctionSpec, FunctionSpecError,
    FunctionTrigger,
};

/// pg_cron extension that owns scheduled trigger fanout. The reconciler
/// guards the catalog with a `CREATE EXTENSION IF NOT EXISTS` to keep the
/// reconcile contract idempotent.
pub const PG_CRON_EXTENSION: &str = "pg_cron";

/// pg_notify channel prefix used when the function trigger is `event`. Each
/// event trigger fans into its own channel so sidecar/edge_functions can
/// subscribe selectively.
pub const FUNCTION_NOTIFY_CHANNEL_PREFIX: &str = "ai_blaise_function_";

/// Sidecar HTTP endpoint that registers the function source with the
/// edge_functions runtime. Plan-side string only; the operator runtime
/// performs the actual HTTP call.
pub const SIDECAR_REGISTER_ENDPOINT: &str = "/functions";

/// Operator-owned metadata tables for function provenance and event-trigger
/// subscriptions. The edge-functions sidecar owns source execution; this plan
/// owns declarative desired state and trigger fanout metadata.
pub const FUNCTION_METADATA_TABLES_SQL: &str = r#"CREATE TABLE IF NOT EXISTS ai_blaise_function_provenance (
    function_name text PRIMARY KEY,
    runtime text NOT NULL,
    http_trigger_count integer NOT NULL,
    scheduled_trigger_count integer NOT NULL,
    event_trigger_count integer NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS ai_blaise_function_event_subscriptions (
    function_name text NOT NULL REFERENCES ai_blaise_function_provenance(function_name) ON DELETE CASCADE,
    table_name text NOT NULL,
    event_kind text NOT NULL,
    notify_channel text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (function_name, table_name, event_kind)
);"#;

/// Step kind that distinguishes sidecar HTTP calls from SQL apply steps.
#[derive(Debug, Clone, Copy, Eq, PartialEq)]
pub enum FunctionStepKind {
    Sidecar,
    Sql,
    Kubernetes,
}

/// Apply step generated by the function reconciler. A step may target the
/// sidecar HTTP API, a SQL apply path, or a Kubernetes object (Service /
/// Ingress) depending on the trigger surface.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct FunctionApplyStep {
    pub name: String,
    pub feature_id: &'static str,
    pub kind: FunctionStepKind,
    pub body: String,
    pub idempotent: bool,
}

impl FunctionApplyStep {
    fn new(
        name: impl Into<String>,
        feature_id: &'static str,
        kind: FunctionStepKind,
        body: impl Into<String>,
        idempotent: bool,
    ) -> Self {
        Self {
            name: name.into(),
            feature_id,
            kind,
            body: body.into(),
            idempotent,
        }
    }
}

/// Apply plan composed of `FunctionApplyStep`s in execution order.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct FunctionApplyPlan {
    pub steps: Vec<FunctionApplyStep>,
}

impl FunctionApplyPlan {
    /// Returns the count of steps for a given kind. Useful for reporting.
    pub fn step_count_of(&self, kind: FunctionStepKind) -> usize {
        self.steps.iter().filter(|step| step.kind == kind).count()
    }
}

/// Sidecar registration payload derived from a `FunctionSpec`. The operator
/// posts this to `POST /functions` on sidecar/edge_functions; the wire format
/// is a stable subset so the runtime can evolve independently.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct FunctionSidecarRegistration {
    pub name: String,
    pub runtime: FunctionRuntime,
    pub source: FunctionSource,
    pub env_secret_refs: Vec<String>,
}

impl FunctionSidecarRegistration {
    /// Render the JSON body posted to the sidecar HTTP API.
    pub fn json_body(&self) -> String {
        let runtime = runtime_label(self.runtime);
        let source = source_json(&self.source);
        let secrets = env_secrets_json(&self.env_secret_refs);
        format!(
            "{{\"name\":\"{name}\",\"runtime\":\"{runtime}\",\"source\":{source},\"env_secret_refs\":{secrets}}}",
            name = json_escape(&self.name),
        )
    }
}

/// HTTP trigger plan generated when a function declares an HTTP trigger.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct FunctionHttpTriggerPlan {
    pub path: String,
    pub service_name: String,
    pub ingress_name: String,
}

/// Scheduled trigger plan generated when a function declares a cron trigger.
/// The reconciler registers a pg_cron job that issues a `pg_notify` on the
/// function-specific channel; the sidecar listens and dispatches.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct FunctionScheduledTriggerPlan {
    pub schedule: String,
    pub job_name: String,
    pub notify_channel: String,
}

/// Event-driven trigger plan generated when a function declares a table
/// event. The reconciler ensures the pg_notify channel exists; the sidecar
/// subscribes through its own listener loop.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct FunctionEventTriggerPlan {
    pub table: String,
    pub event: FunctionEvent,
    pub notify_channel: String,
}

/// Resolved reconcile plan for a `FunctionSpec`.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct FunctionReconcilePlan {
    pub function_name: String,
    pub runtime: FunctionRuntime,
    pub sidecar_registration: FunctionSidecarRegistration,
    pub http_triggers: Vec<FunctionHttpTriggerPlan>,
    pub scheduled_triggers: Vec<FunctionScheduledTriggerPlan>,
    pub event_triggers: Vec<FunctionEventTriggerPlan>,
}

impl TryFrom<&FunctionSpec> for FunctionReconcilePlan {
    type Error = FunctionReconcileError;

    fn try_from(spec: &FunctionSpec) -> Result<Self, Self::Error> {
        spec.validate()?;

        let function_name = spec.name.clone();
        let sidecar_registration = FunctionSidecarRegistration {
            name: function_name.clone(),
            runtime: spec.runtime,
            source: spec.source.clone(),
            env_secret_refs: spec.env_secrets.clone(),
        };

        let mut http_triggers = Vec::new();
        let mut scheduled_triggers = Vec::new();
        let mut event_triggers = Vec::new();

        for trigger in &spec.triggers {
            match trigger {
                FunctionTrigger::Http { path } => {
                    http_triggers.push(FunctionHttpTriggerPlan {
                        path: path.clone(),
                        service_name: format!("{}-fn", sanitize_dns_label(&function_name)),
                        ingress_name: format!("{}-fn", sanitize_dns_label(&function_name)),
                    });
                }
                FunctionTrigger::Scheduled { schedule } => {
                    scheduled_triggers.push(FunctionScheduledTriggerPlan {
                        schedule: schedule.clone(),
                        job_name: format!(
                            "ai_blaise_function_{}_schedule",
                            sanitize_identifier(&function_name)
                        ),
                        notify_channel: notify_channel(&function_name),
                    });
                }
                FunctionTrigger::Event { table, event } => {
                    event_triggers.push(FunctionEventTriggerPlan {
                        table: table.clone(),
                        event: *event,
                        notify_channel: notify_channel(&function_name),
                    });
                }
            }
        }

        Ok(Self {
            function_name,
            runtime: spec.runtime,
            sidecar_registration,
            http_triggers,
            scheduled_triggers,
            event_triggers,
        })
    }
}

impl FunctionReconcilePlan {
    /// Render the apply plan. Sidecar registration is always the first step so
    /// HTTP triggers see a registered function when the gateway routes
    /// requests.
    pub fn apply_plan(&self) -> FunctionApplyPlan {
        let mut steps = vec![FunctionApplyStep::new(
            "register_function_with_sidecar",
            "EF3",
            FunctionStepKind::Sidecar,
            sidecar_request_body(&self.sidecar_registration),
            true,
        )];

        for trigger in &self.http_triggers {
            steps.push(FunctionApplyStep::new(
                "ensure_http_gateway_service",
                "EF3",
                FunctionStepKind::Kubernetes,
                service_manifest(&self.function_name, trigger),
                true,
            ));
            steps.push(FunctionApplyStep::new(
                "ensure_http_gateway_ingress",
                "EF3",
                FunctionStepKind::Kubernetes,
                ingress_manifest(&self.function_name, trigger),
                true,
            ));
        }

        steps.push(FunctionApplyStep::new(
            "ensure_function_metadata_tables",
            "EF3",
            FunctionStepKind::Sql,
            FUNCTION_METADATA_TABLES_SQL,
            true,
        ));

        if !self.scheduled_triggers.is_empty() {
            steps.push(FunctionApplyStep::new(
                "ensure_pg_cron_extension",
                "EF3",
                FunctionStepKind::Sql,
                format!("CREATE EXTENSION IF NOT EXISTS {PG_CRON_EXTENSION};"),
                true,
            ));
        }

        for trigger in &self.scheduled_triggers {
            steps.push(FunctionApplyStep::new(
                "register_scheduled_trigger",
                "EF3",
                FunctionStepKind::Sql,
                schedule_register_sql(trigger),
                true,
            ));
        }

        for trigger in &self.event_triggers {
            steps.push(FunctionApplyStep::new(
                "register_event_trigger",
                "EF3",
                FunctionStepKind::Sql,
                event_register_sql(&self.function_name, trigger),
                true,
            ));
        }

        steps.push(FunctionApplyStep::new(
            "record_function_provenance",
            "EF3",
            FunctionStepKind::Sql,
            record_provenance_sql(self),
            true,
        ));

        FunctionApplyPlan { steps }
    }

    /// Teardown plan executed when the CR is deleted.
    pub fn teardown_steps(&self) -> Vec<FunctionApplyStep> {
        let mut steps = Vec::new();

        for trigger in &self.scheduled_triggers {
            steps.push(FunctionApplyStep::new(
                "unschedule_function_job",
                "EF3",
                FunctionStepKind::Sql,
                format!(
                    "SELECT cron.unschedule({job});",
                    job = sql_literal(&trigger.job_name)
                ),
                true,
            ));
        }

        steps.push(FunctionApplyStep::new(
            "unregister_function_from_sidecar",
            "EF3",
            FunctionStepKind::Sidecar,
            format!(
                "DELETE {endpoint}/{name}",
                endpoint = SIDECAR_REGISTER_ENDPOINT,
                name = self.function_name
            ),
            true,
        ));

        steps.push(FunctionApplyStep::new(
            "delete_function_provenance",
            "EF3",
            FunctionStepKind::Sql,
            format!(
                "DELETE FROM ai_blaise_function_provenance WHERE function_name = {name};",
                name = sql_literal(&self.function_name)
            ),
            true,
        ));

        steps
    }

    /// Returns true when this plan installs a pg_notify-backed trigger.
    pub fn uses_notify_channel(&self) -> bool {
        !self.scheduled_triggers.is_empty() || !self.event_triggers.is_empty()
    }
}

fn sidecar_request_body(registration: &FunctionSidecarRegistration) -> String {
    format!(
        "POST {endpoint} {body}",
        endpoint = SIDECAR_REGISTER_ENDPOINT,
        body = registration.json_body(),
    )
}

fn service_manifest(function_name: &str, trigger: &FunctionHttpTriggerPlan) -> String {
    format!(
        "apiVersion: v1\nkind: Service\nmetadata:\n  name: {service}\n  labels:\n    ai-blaise.com/function: {function}\nspec:\n  selector:\n    app.kubernetes.io/name: ai-blaise-citus-edge-functions\n  ports:\n    - name: http\n      port: 80\n      targetPort: 8080\n",
        service = trigger.service_name,
        function = function_name,
    )
}

fn ingress_manifest(function_name: &str, trigger: &FunctionHttpTriggerPlan) -> String {
    format!(
        "apiVersion: networking.k8s.io/v1\nkind: Ingress\nmetadata:\n  name: {ingress}\n  labels:\n    ai-blaise.com/function: {function}\nspec:\n  rules:\n    - http:\n        paths:\n          - path: {path}\n            pathType: Prefix\n            backend:\n              service:\n                name: {service}\n                port:\n                  number: 80\n",
        ingress = trigger.ingress_name,
        function = function_name,
        path = trigger.path,
        service = trigger.service_name,
    )
}

fn schedule_register_sql(trigger: &FunctionScheduledTriggerPlan) -> String {
    format!(
        "SELECT cron.schedule({job}, {schedule}, format('SELECT pg_notify(%L, %L)', {channel}, {channel}));",
        job = sql_literal(&trigger.job_name),
        schedule = sql_literal(&trigger.schedule),
        channel = sql_literal(&trigger.notify_channel),
    )
}

fn event_register_sql(function_name: &str, trigger: &FunctionEventTriggerPlan) -> String {
    format!(
        "INSERT INTO ai_blaise_function_event_subscriptions (function_name, table_name, event_kind, notify_channel) VALUES ({function}, {table}, {event}, {channel}) ON CONFLICT (function_name, table_name, event_kind) DO UPDATE SET notify_channel = EXCLUDED.notify_channel;",
        function = sql_literal(function_name),
        table = sql_literal(&trigger.table),
        event = sql_literal(event_label(trigger.event)),
        channel = sql_literal(&trigger.notify_channel),
    )
}

fn record_provenance_sql(plan: &FunctionReconcilePlan) -> String {
    format!(
        "INSERT INTO ai_blaise_function_provenance (function_name, runtime, http_trigger_count, scheduled_trigger_count, event_trigger_count) VALUES ({function}, {runtime}, {http}, {scheduled}, {event}) ON CONFLICT (function_name) DO UPDATE SET runtime = EXCLUDED.runtime, http_trigger_count = EXCLUDED.http_trigger_count, scheduled_trigger_count = EXCLUDED.scheduled_trigger_count, event_trigger_count = EXCLUDED.event_trigger_count;",
        function = sql_literal(&plan.function_name),
        runtime = sql_literal(runtime_label(plan.runtime)),
        http = plan.http_triggers.len(),
        scheduled = plan.scheduled_triggers.len(),
        event = plan.event_triggers.len(),
    )
}

fn notify_channel(function_name: &str) -> String {
    format!(
        "{FUNCTION_NOTIFY_CHANNEL_PREFIX}{name}",
        name = sanitize_identifier(function_name)
    )
}

fn runtime_label(runtime: FunctionRuntime) -> &'static str {
    match runtime {
        FunctionRuntime::Deno => "deno",
        FunctionRuntime::Bun => "bun",
    }
}

fn event_label(event: FunctionEvent) -> &'static str {
    match event {
        FunctionEvent::Insert => "INSERT",
        FunctionEvent::Update => "UPDATE",
        FunctionEvent::Delete => "DELETE",
    }
}

fn source_json(source: &FunctionSource) -> String {
    match source {
        FunctionSource::GitRef {
            repository,
            reference,
            path,
        } => format!(
            "{{\"kind\":\"git\",\"repository\":\"{repo}\",\"reference\":\"{reference}\",\"path\":\"{path}\"}}",
            repo = json_escape(repository),
            reference = json_escape(reference),
            path = json_escape(path),
        ),
        FunctionSource::Inline { code } => format!(
            "{{\"kind\":\"inline\",\"code\":\"{code}\"}}",
            code = json_escape(code)
        ),
    }
}

fn env_secrets_json(env_secret_refs: &[String]) -> String {
    let entries = env_secret_refs
        .iter()
        .map(|secret| format!("\"{}\"", json_escape(secret)))
        .collect::<Vec<_>>()
        .join(",");
    format!("[{entries}]")
}

fn sanitize_dns_label(raw: &str) -> String {
    raw.trim()
        .chars()
        .map(|character| match character {
            'A'..='Z' => character.to_ascii_lowercase(),
            'a'..='z' | '0'..='9' | '-' => character,
            _ => '-',
        })
        .collect::<String>()
        .trim_matches('-')
        .to_string()
}

fn sanitize_identifier(raw: &str) -> String {
    raw.trim()
        .chars()
        .map(|character| match character {
            'A'..='Z' => character.to_ascii_lowercase(),
            'a'..='z' | '0'..='9' | '_' => character,
            _ => '_',
        })
        .collect::<String>()
        .trim_matches('_')
        .to_string()
}

fn sql_literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn json_escape(value: &str) -> String {
    value
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r")
        .replace('\t', "\\t")
}

#[derive(Debug, Clone, Eq, PartialEq)]
pub enum FunctionReconcileError {
    InvalidSpec(FunctionSpecError),
}

impl fmt::Display for FunctionReconcileError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidSpec(error) => write!(formatter, "{error}"),
        }
    }
}

impl Error for FunctionReconcileError {}

impl From<FunctionSpecError> for FunctionReconcileError {
    fn from(error: FunctionSpecError) -> Self {
        Self::InvalidSpec(error)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn http_function_spec() -> FunctionSpec {
        FunctionSpec {
            name: "order-created".to_string(),
            runtime: FunctionRuntime::Deno,
            source: FunctionSource::GitRef {
                repository: "https://github.com/ai-blaise/functions".to_string(),
                reference: "main".to_string(),
                path: "orders/index.ts".to_string(),
            },
            triggers: vec![FunctionTrigger::Http {
                path: "/orders".to_string(),
            }],
            env_secrets: vec!["orders-api-key".to_string()],
        }
    }

    fn full_function_spec() -> FunctionSpec {
        FunctionSpec {
            name: "billing-sweep".to_string(),
            runtime: FunctionRuntime::Bun,
            source: FunctionSource::Inline {
                code: "export default { fetch: () => new Response('ok') }".to_string(),
            },
            triggers: vec![
                FunctionTrigger::Http {
                    path: "/billing/sweep".to_string(),
                },
                FunctionTrigger::Scheduled {
                    schedule: "0 * * * *".to_string(),
                },
                FunctionTrigger::Event {
                    table: "public.orders".to_string(),
                    event: FunctionEvent::Insert,
                },
            ],
            env_secrets: Vec::new(),
        }
    }

    #[test]
    fn http_only_plan_emits_service_and_ingress_steps() {
        let plan = FunctionReconcilePlan::try_from(&http_function_spec()).expect("valid plan");

        assert_eq!(plan.function_name, "order-created");
        assert_eq!(plan.http_triggers.len(), 1);
        assert!(plan.scheduled_triggers.is_empty());
        assert!(plan.event_triggers.is_empty());
        assert!(!plan.uses_notify_channel());

        let apply_plan = plan.apply_plan();
        let names: Vec<&str> = apply_plan
            .steps
            .iter()
            .map(|step| step.name.as_str())
            .collect();
        assert_eq!(
            names,
            vec![
                "register_function_with_sidecar",
                "ensure_http_gateway_service",
                "ensure_http_gateway_ingress",
                "ensure_function_metadata_tables",
                "record_function_provenance",
            ]
        );
        assert_eq!(
            apply_plan.step_count_of(FunctionStepKind::Sidecar),
            1,
            "exactly one sidecar registration step"
        );
        assert_eq!(
            apply_plan.step_count_of(FunctionStepKind::Kubernetes),
            2,
            "service + ingress",
        );
        assert!(apply_plan
            .steps
            .iter()
            .any(|step| step.body.contains("ai_blaise_function_provenance")));
        assert!(apply_plan
            .steps
            .iter()
            .any(|step| step.body.contains("POST /functions")));
        assert!(apply_plan
            .steps
            .iter()
            .any(|step| step.body.contains("kind: Service")));
        assert!(apply_plan
            .steps
            .iter()
            .any(|step| step.body.contains("kind: Ingress")));
    }

    #[test]
    fn full_plan_emits_pg_cron_and_event_subscriptions() {
        let plan = FunctionReconcilePlan::try_from(&full_function_spec()).expect("valid plan");

        assert!(plan.uses_notify_channel());

        let apply_plan = plan.apply_plan();
        assert!(apply_plan.steps.iter().any(|step| step
            .body
            .contains("CREATE EXTENSION IF NOT EXISTS pg_cron;")));
        assert!(apply_plan
            .steps
            .iter()
            .any(|step| step.body.contains("cron.schedule")));
        assert!(apply_plan
            .steps
            .iter()
            .any(|step| step.body.contains("ai_blaise_function_event_subscriptions")));
        assert!(apply_plan
            .steps
            .iter()
            .any(|step| step.body.contains("'bun'")));
        assert!(apply_plan
            .steps
            .iter()
            .any(|step| step.body.contains("ai_blaise_function_provenance")));
    }

    #[test]
    fn teardown_steps_drop_sidecar_and_cron_jobs() {
        let plan = FunctionReconcilePlan::try_from(&full_function_spec()).expect("valid plan");
        let teardown = plan.teardown_steps();
        let names: Vec<&str> = teardown.iter().map(|step| step.name.as_str()).collect();
        assert!(names.contains(&"unschedule_function_job"));
        assert!(names.contains(&"unregister_function_from_sidecar"));
        assert!(names.contains(&"delete_function_provenance"));
    }

    #[test]
    fn invalid_spec_propagates_validation_error() {
        let mut spec = http_function_spec();
        spec.triggers.clear();
        assert_eq!(
            FunctionReconcilePlan::try_from(&spec),
            Err(FunctionReconcileError::InvalidSpec(
                FunctionSpecError::MissingRequiredField("triggers")
            ))
        );
    }

    #[test]
    fn function_name_propagates_to_notify_channel_and_sidecar_payload() {
        let mut spec = full_function_spec();
        spec.name = "Billing Sweep".to_string();
        let plan = FunctionReconcilePlan::try_from(&spec).expect("valid plan");
        assert_eq!(
            plan.scheduled_triggers[0].notify_channel,
            "ai_blaise_function_billing_sweep"
        );
        assert!(plan
            .sidecar_registration
            .json_body()
            .contains("\"name\":\"Billing Sweep\""));
    }
}
