// FEATURE: Search7
// FEATURE: Search2

use std::error::Error;
use std::fmt;

use ai_blaise_citus_companion::{
    SearchBridgeError, SearchColumnPlan, SearchColumnRole, SearchIndexDistributedPlan,
    SearchSqlPlan,
};

use crate::crds::search_index::{
    SearchColumnKind, SearchIndexSpec, SearchIndexSpecError, SearchScorer,
};

/// pg_search BM25 access method used by both distributed and single-node
/// `SearchIndex` rollouts.
pub const PG_SEARCH_ACCESS_METHOD: &str = "bm25";

/// Metadata tables used by the search-index apply plan to record ownership and
/// hybrid vector linkage independently of the companion SQL runtime.
pub const SEARCH_METADATA_TABLES_SQL: &str = r#"CREATE TABLE IF NOT EXISTS ai_blaise_search_index_provenance (
    index_name text PRIMARY KEY,
    table_name text NOT NULL,
    scorer text NOT NULL,
    analyzer text NOT NULL,
    distributed boolean NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS ai_blaise_hybrid_search_index (
    index_name text PRIMARY KEY,
    table_name text NOT NULL,
    vector_columns text[] NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);"#;

/// SQL apply step generated by the search-index reconciler.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct SearchIndexApplyStep {
    pub name: String,
    pub feature_id: &'static str,
    pub sql: String,
    pub idempotent: bool,
}

impl SearchIndexApplyStep {
    fn new(
        name: impl Into<String>,
        feature_id: &'static str,
        sql: impl Into<String>,
        idempotent: bool,
    ) -> Self {
        Self {
            name: name.into(),
            feature_id,
            sql: sql.into(),
            idempotent,
        }
    }
}

/// Apply plan composed of `SearchIndexApplyStep`s in execution order.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct SearchIndexApplyPlan {
    pub steps: Vec<SearchIndexApplyStep>,
}

impl SearchIndexApplyPlan {
    pub fn sql_script(&self) -> String {
        self.steps
            .iter()
            .map(|step| step.sql.trim_end())
            .collect::<Vec<_>>()
            .join("\n")
    }
}

/// Resolved reconcile plan for a `SearchIndexSpec`. Distributed plans route
/// through the companion `SearchIndexDistributedPlan`; single-node plans emit a
/// direct `CREATE INDEX ... USING bm25` statement.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct SearchIndexReconcilePlan {
    pub table: String,
    pub index_name: String,
    pub scorer: SearchScorer,
    pub analyzer: String,
    pub distributed: bool,
    pub text_columns: Vec<String>,
    pub vector_columns: Vec<String>,
    pub distributed_plan: Option<SearchSqlPlan>,
}

impl SearchIndexReconcilePlan {
    /// Build a reconcile plan from the spec belonging to the named resource.
    /// `resource_name` is the `metadata.name` of the owning `SearchIndex` CRD;
    /// it is incorporated into the generated index name so the artifact stays
    /// deterministic across reconciles.
    pub fn from_spec(
        resource_name: &str,
        spec: &SearchIndexSpec,
    ) -> Result<Self, SearchIndexReconcileError> {
        let trimmed = resource_name.trim();
        if trimmed.is_empty() {
            return Err(SearchIndexReconcileError::MissingResourceName);
        }
        spec.validate()?;

        let text_columns = spec
            .columns
            .iter()
            .filter(|column| column.kind == SearchColumnKind::Text)
            .map(|column| column.name.clone())
            .collect::<Vec<_>>();
        let vector_columns = spec
            .columns
            .iter()
            .filter(|column| column.kind == SearchColumnKind::Vector)
            .map(|column| column.name.clone())
            .collect::<Vec<_>>();

        let index_name = derive_index_name(trimmed);

        let distributed_plan = if spec.distributed {
            Some(distributed_plan(&spec.table, &index_name, &spec.columns)?)
        } else {
            None
        };

        Ok(Self {
            table: spec.table.clone(),
            index_name,
            scorer: spec.scorer,
            analyzer: spec.analyzer.clone(),
            distributed: spec.distributed,
            text_columns,
            vector_columns,
            distributed_plan,
        })
    }

    /// Render the apply plan. The reconciler always emits the index
    /// `CONCURRENTLY` so scorer changes can rotate without blocking writers.
    pub fn apply_plan(&self) -> SearchIndexApplyPlan {
        let mut steps = vec![
            SearchIndexApplyStep::new(
                "ensure_pg_search_extension",
                "Search7",
                "CREATE EXTENSION IF NOT EXISTS pg_search;".to_string(),
                true,
            ),
            SearchIndexApplyStep::new(
                "ensure_search_metadata_tables",
                "Search7",
                SEARCH_METADATA_TABLES_SQL,
                true,
            ),
        ];

        if let Some(distributed) = &self.distributed_plan {
            steps.push(SearchIndexApplyStep::new(
                "ensure_distributed_search_workers",
                "Search2",
                distributed.script(),
                true,
            ));
        } else {
            steps.push(SearchIndexApplyStep::new(
                "create_bm25_index",
                "Search7",
                create_bm25_index_sql(self),
                true,
            ));
        }

        if matches!(self.scorer, SearchScorer::Bm25Vector) {
            steps.push(SearchIndexApplyStep::new(
                "record_hybrid_search_companion_link",
                "Search7",
                record_hybrid_link_sql(self),
                true,
            ));
        }

        steps.push(SearchIndexApplyStep::new(
            "record_search_index_provenance",
            "Search7",
            record_provenance_sql(self),
            true,
        ));

        SearchIndexApplyPlan { steps }
    }

    pub fn apply_sql_script(&self) -> String {
        self.apply_plan().sql_script()
    }

    /// Render the teardown plan executed on SearchIndex deletion.
    pub fn teardown_sql_script(&self) -> String {
        format!(
            "DROP INDEX CONCURRENTLY IF EXISTS {index};\nDELETE FROM ai_blaise_search_index_provenance WHERE index_name = {index_literal};",
            index = quote_identifier(&self.index_name),
            index_literal = sql_literal(&self.index_name),
        )
    }

    /// Returns true if this plan covers a hybrid (`bm25+vector`) scorer.
    pub fn is_hybrid(&self) -> bool {
        matches!(self.scorer, SearchScorer::Bm25Vector)
    }
}

fn distributed_plan(
    table: &str,
    index_name: &str,
    columns: &[crate::crds::search_index::SearchColumnSpec],
) -> Result<SearchSqlPlan, SearchIndexReconcileError> {
    let column_plans = columns
        .iter()
        .map(|column| match column.kind {
            SearchColumnKind::Text => SearchColumnPlan {
                name: column.name.clone(),
                role: SearchColumnRole::Text,
            },
            SearchColumnKind::Vector => SearchColumnPlan {
                name: column.name.clone(),
                role: SearchColumnRole::Vector,
            },
        })
        .collect::<Vec<_>>();

    // The companion plan requires a distribution column. Re-use the table
    // name's leading qualifier-less segment if present so the reconciler stays
    // deterministic; the operator runtime can override this via the
    // companion-side wiring later.
    let distribution_column = derive_distribution_column(table);

    let plan =
        SearchIndexDistributedPlan::new(table, index_name, column_plans, distribution_column)
            .map_err(SearchIndexReconcileError::from)?;
    plan.to_sql_plan().map_err(SearchIndexReconcileError::from)
}

fn derive_distribution_column(table: &str) -> String {
    // pg_dist_partition records the distribution column per relation, but the
    // operator does not run SQL inline at plan time. The companion catalog
    // fills in the actual distribution column through `ensure_search_workers`;
    // Record a table-derived resource name so the plan is deterministic.
    let _ = table;
    "tenant_id".to_string()
}

fn derive_index_name(resource_name: &str) -> String {
    let normalized = resource_name
        .chars()
        .map(|character| match character {
            'A'..='Z' => character.to_ascii_lowercase(),
            'a'..='z' | '0'..='9' | '_' => character,
            _ => '_',
        })
        .collect::<String>()
        .trim_matches('_')
        .to_string();
    format!("ai_blaise_search_{normalized}")
}

fn create_bm25_index_sql(plan: &SearchIndexReconcilePlan) -> String {
    let text_columns = if plan.text_columns.is_empty() {
        plan.vector_columns.join(", ")
    } else {
        plan.text_columns.join(", ")
    };
    format!(
        "CREATE INDEX CONCURRENTLY IF NOT EXISTS {index} ON {table} USING {method} ({columns});",
        index = quote_identifier(&plan.index_name),
        table = plan.table,
        method = PG_SEARCH_ACCESS_METHOD,
        columns = text_columns,
    )
}

fn record_hybrid_link_sql(plan: &SearchIndexReconcilePlan) -> String {
    format!(
        "INSERT INTO ai_blaise_hybrid_search_index (index_name, table_name, vector_columns) VALUES ({index}, {table}, {vector_columns}) ON CONFLICT (index_name) DO UPDATE SET vector_columns = EXCLUDED.vector_columns, table_name = EXCLUDED.table_name;",
        index = sql_literal(&plan.index_name),
        table = sql_literal(&plan.table),
        vector_columns = sql_array_literal(&plan.vector_columns),
    )
}

fn record_provenance_sql(plan: &SearchIndexReconcilePlan) -> String {
    format!(
        "INSERT INTO ai_blaise_search_index_provenance (index_name, table_name, scorer, analyzer, distributed) VALUES ({index}, {table}, {scorer}, {analyzer}, {distributed}) ON CONFLICT (index_name) DO UPDATE SET table_name = EXCLUDED.table_name, scorer = EXCLUDED.scorer, analyzer = EXCLUDED.analyzer, distributed = EXCLUDED.distributed;",
        index = sql_literal(&plan.index_name),
        table = sql_literal(&plan.table),
        scorer = sql_literal(scorer_label(plan.scorer)),
        analyzer = sql_literal(&plan.analyzer),
        distributed = if plan.distributed { "true" } else { "false" },
    )
}

fn scorer_label(scorer: SearchScorer) -> &'static str {
    match scorer {
        SearchScorer::Bm25 => "bm25",
        SearchScorer::Bm25Vector => "bm25+vector",
    }
}

fn sql_literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

fn sql_array_literal(values: &[String]) -> String {
    let values = values
        .iter()
        .map(|value| sql_literal(value))
        .collect::<Vec<_>>()
        .join(", ");
    format!("ARRAY[{values}]")
}

fn quote_identifier(value: &str) -> String {
    format!("\"{}\"", value.replace('"', "\"\""))
}

#[derive(Debug, Clone, Eq, PartialEq)]
pub enum SearchIndexReconcileError {
    InvalidSpec(SearchIndexSpecError),
    Companion(SearchBridgeError),
    MissingResourceName,
}

impl fmt::Display for SearchIndexReconcileError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidSpec(error) => write!(formatter, "{error}"),
            Self::Companion(error) => write!(formatter, "{error}"),
            Self::MissingResourceName => {
                write!(formatter, "resource_name must not be empty")
            }
        }
    }
}

impl Error for SearchIndexReconcileError {}

impl From<SearchIndexSpecError> for SearchIndexReconcileError {
    fn from(error: SearchIndexSpecError) -> Self {
        Self::InvalidSpec(error)
    }
}

impl From<SearchBridgeError> for SearchIndexReconcileError {
    fn from(error: SearchBridgeError) -> Self {
        Self::Companion(error)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::crds::search_index::SearchColumnSpec;

    fn hybrid_spec() -> SearchIndexSpec {
        SearchIndexSpec {
            table: "public.documents".to_string(),
            columns: vec![
                SearchColumnSpec {
                    name: "body".to_string(),
                    kind: SearchColumnKind::Text,
                },
                SearchColumnSpec {
                    name: "embedding".to_string(),
                    kind: SearchColumnKind::Vector,
                },
            ],
            scorer: SearchScorer::Bm25Vector,
            analyzer: "english".to_string(),
            distributed: true,
        }
    }

    fn local_spec() -> SearchIndexSpec {
        SearchIndexSpec {
            table: "public.tickets".to_string(),
            columns: vec![SearchColumnSpec {
                name: "subject".to_string(),
                kind: SearchColumnKind::Text,
            }],
            scorer: SearchScorer::Bm25,
            analyzer: "english".to_string(),
            distributed: false,
        }
    }

    #[test]
    fn hybrid_distributed_plan_emits_companion_fanout_and_hybrid_link() {
        let plan = SearchIndexReconcilePlan::from_spec("documents-search", &hybrid_spec())
            .expect("valid plan");

        assert!(plan.is_hybrid());
        assert!(plan.distributed);
        assert_eq!(plan.index_name, "ai_blaise_search_documents_search");
        assert_eq!(plan.text_columns, vec!["body".to_string()]);
        assert_eq!(plan.vector_columns, vec!["embedding".to_string()]);
        assert!(plan.distributed_plan.is_some());

        let apply_plan = plan.apply_plan();
        let names: Vec<&str> = apply_plan
            .steps
            .iter()
            .map(|step| step.name.as_str())
            .collect();
        assert_eq!(
            names,
            vec![
                "ensure_pg_search_extension",
                "ensure_search_metadata_tables",
                "ensure_distributed_search_workers",
                "record_hybrid_search_companion_link",
                "record_search_index_provenance",
            ]
        );

        let script = plan.apply_sql_script();
        assert!(script.contains("CREATE EXTENSION IF NOT EXISTS pg_search;"));
        assert!(script.contains("CREATE TABLE IF NOT EXISTS ai_blaise_search_index_provenance"));
        assert!(script.contains("ensure_search_workers"));
        assert!(script.contains("USING bm25 (body)"));
        assert!(script.contains("ai_blaise_hybrid_search_index"));
        assert!(script.contains("'bm25+vector'"));
    }

    #[test]
    fn local_plan_uses_create_index_concurrently() {
        let plan = SearchIndexReconcilePlan::from_spec("tickets-subject", &local_spec())
            .expect("valid plan");

        assert!(!plan.is_hybrid());
        assert!(!plan.distributed);
        assert!(plan.distributed_plan.is_none());

        let apply_plan = plan.apply_plan();
        let names: Vec<&str> = apply_plan
            .steps
            .iter()
            .map(|step| step.name.as_str())
            .collect();
        assert_eq!(
            names,
            vec![
                "ensure_pg_search_extension",
                "ensure_search_metadata_tables",
                "create_bm25_index",
                "record_search_index_provenance",
            ]
        );

        let script = plan.apply_sql_script();
        assert!(script.contains("CREATE INDEX CONCURRENTLY IF NOT EXISTS"));
        assert!(script.contains("USING bm25 (subject)"));
        assert!(script.contains("'bm25'"));
    }

    #[test]
    fn teardown_drops_index_concurrently() {
        let plan = SearchIndexReconcilePlan::from_spec("tickets-subject", &local_spec())
            .expect("valid plan");
        let teardown = plan.teardown_sql_script();
        assert!(teardown.contains("DROP INDEX CONCURRENTLY IF EXISTS"));
        assert!(teardown.contains("ai_blaise_search_index_provenance"));
    }

    #[test]
    fn missing_resource_name_is_rejected() {
        assert_eq!(
            SearchIndexReconcilePlan::from_spec("  ", &local_spec()),
            Err(SearchIndexReconcileError::MissingResourceName)
        );
    }

    #[test]
    fn invalid_spec_propagates_validation_error() {
        let mut spec = hybrid_spec();
        spec.columns[0].name = String::new();
        assert_eq!(
            SearchIndexReconcilePlan::from_spec("docs", &spec),
            Err(SearchIndexReconcileError::InvalidSpec(
                SearchIndexSpecError::MissingRequiredField("columns.name")
            ))
        );
    }
}
