// FEATURE: S2

use std::error::Error;
use std::fmt;

use crate::crds::shard_group::{
    PlacementPolicy, ShardGroupSpec, ShardGroupSpecError, UnsatisfiablePlacementAction,
};

/// SQL function name used to create a distributed table for a shard group.
pub const CITUS_CREATE_DISTRIBUTED_TABLE: &str = "create_distributed_table";

/// SQL function name used to update colocation for an existing distributed
/// table.
pub const CITUS_UPDATE_COLOCATION: &str = "update_distributed_table_colocation";

/// GUC name used to configure the replication factor before the distributed
/// table is created.
pub const CITUS_REPLICATION_FACTOR_GUC: &str = "citus.shard_replication_factor";

/// GUC name used to configure the shard count before the distributed table is
/// created.
pub const CITUS_SHARD_COUNT_GUC: &str = "citus.shard_count";

/// Topology-spread constraint plan derived from a `ShardGroupSpec`.
///
/// Each entry corresponds 1:1 with a Kubernetes `TopologySpreadConstraint`
/// applied to the CNPG cluster's StatefulSet pods (and to any pool/sidecar
/// Deployments that host the shard placements).
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct TopologySpreadConstraintPlan {
    pub topology_key: String,
    pub max_skew: u32,
    pub when_unsatisfiable: UnsatisfiablePlacementAction,
}

impl TopologySpreadConstraintPlan {
    fn from_policy(policy: &PlacementPolicy) -> Self {
        Self {
            topology_key: policy.topology_key.clone(),
            max_skew: policy.max_skew,
            when_unsatisfiable: policy.when_unsatisfiable,
        }
    }

    /// Kubernetes-style serialization for the constraint.
    pub fn when_unsatisfiable_str(&self) -> &'static str {
        match self.when_unsatisfiable {
            UnsatisfiablePlacementAction::DoNotSchedule => "DoNotSchedule",
            UnsatisfiablePlacementAction::ScheduleAnyway => "ScheduleAnyway",
        }
    }
}

/// SQL apply step generated by the shard-group reconciler.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct ShardGroupApplyStep {
    pub name: String,
    pub sql: String,
    pub idempotent: bool,
}

impl ShardGroupApplyStep {
    fn new(name: impl Into<String>, sql: impl Into<String>, idempotent: bool) -> Self {
        Self {
            name: name.into(),
            sql: sql.into(),
            idempotent,
        }
    }
}

/// Apply plan composed of `ShardGroupApplyStep`s in execution order.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct ShardGroupApplyPlan {
    pub steps: Vec<ShardGroupApplyStep>,
}

impl ShardGroupApplyPlan {
    pub fn sql_script(&self) -> String {
        self.steps
            .iter()
            .map(|step| step.sql.trim_end())
            .collect::<Vec<_>>()
            .join("\n")
    }
}

/// Resolved reconcile plan for a `ShardGroupSpec`.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct ShardGroupReconcilePlan {
    pub parent_table: String,
    pub distribution_column: String,
    pub num_shards: u32,
    pub replication_factor: u32,
    pub colocation_group: Option<String>,
    pub topology_constraints: Vec<TopologySpreadConstraintPlan>,
}

impl TryFrom<&ShardGroupSpec> for ShardGroupReconcilePlan {
    type Error = ShardGroupReconcileError;

    fn try_from(spec: &ShardGroupSpec) -> Result<Self, Self::Error> {
        spec.validate()?;

        let topology_constraints = spec
            .placement_policy
            .iter()
            .map(TopologySpreadConstraintPlan::from_policy)
            .collect();

        Ok(Self {
            parent_table: spec.parent_table.clone(),
            distribution_column: spec.distribution_column.clone(),
            num_shards: spec.num_shards,
            replication_factor: spec.replication_factor,
            colocation_group: spec.colocation_group.clone(),
            topology_constraints,
        })
    }
}

impl ShardGroupReconcilePlan {
    /// Number of derived topology-spread constraints. Equal to
    /// `spec.placement_policy.len()`.
    pub fn topology_constraint_count(&self) -> usize {
        self.topology_constraints.len()
    }

    /// True when at least one constraint refuses to schedule replicas if the
    /// skew bound is violated. Useful for status reporting.
    pub fn has_hard_constraint(&self) -> bool {
        self.topology_constraints.iter().any(|constraint| {
            matches!(
                constraint.when_unsatisfiable,
                UnsatisfiablePlacementAction::DoNotSchedule
            )
        })
    }

    /// Render the SQL apply plan that creates the distributed table, sets the
    /// shard/colocation GUCs, and emits a guard so the operator can detect a
    /// missing distributed table on re-reconcile.
    pub fn apply_plan(&self) -> ShardGroupApplyPlan {
        let mut steps = vec![
            ShardGroupApplyStep::new(
                "set_shard_count",
                format!(
                    "SET LOCAL {guc} = {count};",
                    guc = CITUS_SHARD_COUNT_GUC,
                    count = self.num_shards
                ),
                true,
            ),
            ShardGroupApplyStep::new(
                "set_shard_replication_factor",
                format!(
                    "SET LOCAL {guc} = {factor};",
                    guc = CITUS_REPLICATION_FACTOR_GUC,
                    factor = self.replication_factor
                ),
                true,
            ),
            ShardGroupApplyStep::new(
                "create_distributed_table",
                create_distributed_table_sql(self),
                false,
            ),
        ];

        if let Some(colocation_group) = &self.colocation_group {
            steps.push(ShardGroupApplyStep::new(
                "update_colocation_group",
                update_colocation_sql(self, colocation_group),
                true,
            ));
        }

        steps.push(ShardGroupApplyStep::new(
            "verify_distributed_table",
            verify_distributed_table_sql(self),
            true,
        ));

        ShardGroupApplyPlan { steps }
    }

    /// Render the apply plan SQL script directly. Convenience wrapper around
    /// `apply_plan().sql_script()`.
    pub fn apply_sql_script(&self) -> String {
        self.apply_plan().sql_script()
    }

    /// Render the topology-spread constraints as a Kubernetes-style YAML
    /// fragment that can be inlined into Deployment/StatefulSet pod specs.
    pub fn topology_constraints_yaml(&self) -> String {
        if self.topology_constraints.is_empty() {
            return String::new();
        }

        let lines: Vec<String> = self
            .topology_constraints
            .iter()
            .map(|constraint| {
                format!(
                    "- maxSkew: {skew}\n  topologyKey: {key}\n  whenUnsatisfiable: {action}",
                    skew = constraint.max_skew,
                    key = constraint.topology_key,
                    action = constraint.when_unsatisfiable_str()
                )
            })
            .collect();

        lines.join("\n")
    }
}

fn create_distributed_table_sql(plan: &ShardGroupReconcilePlan) -> String {
    let mut call = format!(
        "SELECT {function}({table}, {column}",
        function = CITUS_CREATE_DISTRIBUTED_TABLE,
        table = sql_literal(&plan.parent_table),
        column = sql_literal(&plan.distribution_column),
    );

    if let Some(colocation_group) = &plan.colocation_group {
        call.push_str(", colocate_with => ");
        call.push_str(&sql_literal(colocation_group));
    }

    call.push_str(");");
    call
}

fn update_colocation_sql(plan: &ShardGroupReconcilePlan, colocation_group: &str) -> String {
    format!(
        "SELECT {function}({table}, colocate_with => {colocation});",
        function = CITUS_UPDATE_COLOCATION,
        table = sql_literal(&plan.parent_table),
        colocation = sql_literal(colocation_group),
    )
}

fn verify_distributed_table_sql(plan: &ShardGroupReconcilePlan) -> String {
    format!(
        r"DO $ai_blaise_citus_shard_group$
DECLARE
    found_shard_count integer;
BEGIN
    SELECT count(*) INTO found_shard_count
    FROM pg_catalog.pg_dist_shard
    WHERE logicalrelid = {table}::regclass;

    IF found_shard_count = 0 THEN
        RAISE EXCEPTION 'shard group {parent} reconcile failed: no shards in pg_dist_shard';
    END IF;

    IF found_shard_count <> {expected} THEN
        RAISE EXCEPTION 'shard group {parent} reconcile failed: expected % shards, found %',
            {expected}, found_shard_count;
    END IF;
END
$ai_blaise_citus_shard_group$;",
        table = sql_literal(&plan.parent_table),
        parent = plan.parent_table,
        expected = plan.num_shards,
    )
}

fn sql_literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

#[derive(Debug, Clone, Eq, PartialEq)]
pub enum ShardGroupReconcileError {
    InvalidSpec(ShardGroupSpecError),
}

impl fmt::Display for ShardGroupReconcileError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidSpec(error) => write!(formatter, "{error}"),
        }
    }
}

impl Error for ShardGroupReconcileError {}

impl From<ShardGroupSpecError> for ShardGroupReconcileError {
    fn from(error: ShardGroupSpecError) -> Self {
        Self::InvalidSpec(error)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn reconcile_plan_maps_spec_to_topology_and_sql() {
        let spec = ShardGroupSpec {
            parent_table: "public.metrics".to_string(),
            distribution_column: "tenant_id".to_string(),
            num_shards: 32,
            colocation_group: Some("metrics".to_string()),
            replication_factor: 3,
            placement_policy: vec![
                PlacementPolicy {
                    topology_key: "topology.kubernetes.io/zone".to_string(),
                    max_skew: 1,
                    when_unsatisfiable: UnsatisfiablePlacementAction::DoNotSchedule,
                },
                PlacementPolicy {
                    topology_key: "kubernetes.io/hostname".to_string(),
                    max_skew: 2,
                    when_unsatisfiable: UnsatisfiablePlacementAction::ScheduleAnyway,
                },
            ],
        };

        let plan = ShardGroupReconcilePlan::try_from(&spec).expect("valid plan");

        assert_eq!(plan.num_shards, 32);
        assert_eq!(plan.replication_factor, 3);
        assert_eq!(plan.colocation_group.as_deref(), Some("metrics"));
        assert_eq!(plan.topology_constraint_count(), 2);
        assert!(plan.has_hard_constraint());

        let constraints_yaml = plan.topology_constraints_yaml();
        assert!(constraints_yaml.contains("topology.kubernetes.io/zone"));
        assert!(constraints_yaml.contains("whenUnsatisfiable: DoNotSchedule"));
        assert!(constraints_yaml.contains("kubernetes.io/hostname"));
        assert!(constraints_yaml.contains("whenUnsatisfiable: ScheduleAnyway"));

        let apply_plan = plan.apply_plan();
        assert_eq!(apply_plan.steps.len(), 5);
        assert_eq!(apply_plan.steps[0].name, "set_shard_count");
        assert!(apply_plan.steps[0].sql.contains("citus.shard_count = 32"));
        assert!(apply_plan.steps[0].idempotent);
        assert_eq!(apply_plan.steps[1].name, "set_shard_replication_factor");
        assert!(apply_plan.steps[1]
            .sql
            .contains("citus.shard_replication_factor = 3"));
        assert_eq!(apply_plan.steps[2].name, "create_distributed_table");
        assert!(!apply_plan.steps[2].idempotent);
        assert!(apply_plan.steps[2].sql.contains("create_distributed_table"));
        assert!(apply_plan.steps[2].sql.contains("'public.metrics'"));
        assert!(apply_plan.steps[2].sql.contains("'tenant_id'"));
        assert!(apply_plan.steps[2]
            .sql
            .contains("colocate_with => 'metrics'"));
        assert_eq!(apply_plan.steps[3].name, "update_colocation_group");
        assert!(apply_plan.steps[3].idempotent);
        assert!(apply_plan.steps[3]
            .sql
            .contains("update_distributed_table_colocation"));
        assert_eq!(apply_plan.steps[4].name, "verify_distributed_table");
        assert!(apply_plan.steps[4].sql.contains("pg_dist_shard"));
        assert!(apply_plan.steps[4].sql.contains("expected % shards"));

        let script = plan.apply_sql_script();
        assert!(script.contains("SET LOCAL citus.shard_count = 32;"));
        assert!(script.contains("SET LOCAL citus.shard_replication_factor = 3;"));
        assert!(script.contains("create_distributed_table"));
        assert!(script.contains("update_distributed_table_colocation"));
        assert!(script.contains("pg_dist_shard"));
    }

    #[test]
    fn reconcile_plan_without_colocation_skips_update_step() {
        let spec = ShardGroupSpec {
            parent_table: "public.orders".to_string(),
            distribution_column: "tenant_id".to_string(),
            num_shards: 16,
            colocation_group: None,
            replication_factor: 1,
            placement_policy: Vec::new(),
        };

        let plan = ShardGroupReconcilePlan::try_from(&spec).expect("valid plan");

        assert_eq!(plan.topology_constraint_count(), 0);
        assert!(!plan.has_hard_constraint());

        let apply_plan = plan.apply_plan();
        assert_eq!(apply_plan.steps.len(), 4);
        let names: Vec<&str> = apply_plan
            .steps
            .iter()
            .map(|step| step.name.as_str())
            .collect();
        assert_eq!(
            names,
            vec![
                "set_shard_count",
                "set_shard_replication_factor",
                "create_distributed_table",
                "verify_distributed_table",
            ]
        );
        assert!(!apply_plan.steps[2].sql.contains("colocate_with"));
        assert_eq!(plan.topology_constraints_yaml(), "");
    }

    #[test]
    fn reconcile_plan_rejects_zero_shards() {
        let spec = ShardGroupSpec {
            parent_table: "public.metrics".to_string(),
            distribution_column: "tenant_id".to_string(),
            num_shards: 0,
            colocation_group: None,
            replication_factor: 1,
            placement_policy: Vec::new(),
        };

        assert_eq!(
            ShardGroupReconcilePlan::try_from(&spec),
            Err(ShardGroupReconcileError::InvalidSpec(
                ShardGroupSpecError::InvalidShardCount
            ))
        );
    }

    #[test]
    fn quoted_table_name_is_escaped() {
        let spec = ShardGroupSpec {
            parent_table: "public.\"weird'name\"".to_string(),
            distribution_column: "tenant_id".to_string(),
            num_shards: 4,
            colocation_group: None,
            replication_factor: 1,
            placement_policy: Vec::new(),
        };

        let plan = ShardGroupReconcilePlan::try_from(&spec).expect("valid plan");
        let script = plan.apply_sql_script();
        assert!(script.contains("'public.\"weird''name\"'"));
    }
}
