// FEATURE: WH1
// FEATURE: WH2

use std::error::Error;
use std::fmt;

use ai_blaise_citus_companion::{
    WebhookError as CompanionWebhookError, WebhookEvent as CompanionWebhookEvent, WebhookHeader,
    WebhookRegistrationPlan, WebhookSqlPlan,
};

#[cfg(test)]
use crate::crds::webhook::WebhookRetryPolicy;
use crate::crds::webhook::{WebhookEvent, WebhookSpec, WebhookSpecError};

/// Companion-managed queue table used to buffer webhook events before
/// sidecar/cdc drains and posts them. Centralized so the reconciler does not
/// silently diverge from the companion SQL surface.
pub const WEBHOOK_QUEUE: &str = "companion.webhook_queue";

/// Operator-owned metadata tables for webhook CR provenance, payload template
/// tracking, and dead-letter target tracking. The companion extension owns the
/// actual queue and trigger tables.
pub const WEBHOOK_METADATA_TABLES_SQL: &str = r#"CREATE TABLE IF NOT EXISTS ai_blaise_webhook_provenance (
    webhook_name text PRIMARY KEY,
    table_name text NOT NULL,
    url text NOT NULL,
    events text[] NOT NULL,
    max_attempts integer NOT NULL,
    backoff text NOT NULL,
    headers_secret_ref text,
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS ai_blaise_webhook_payload_templates (
    webhook_name text PRIMARY KEY REFERENCES ai_blaise_webhook_provenance(webhook_name) ON DELETE CASCADE,
    payload_template text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS ai_blaise_webhook_dead_letter_targets (
    webhook_name text PRIMARY KEY REFERENCES ai_blaise_webhook_provenance(webhook_name) ON DELETE CASCADE,
    dead_letter_table text NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);"#;

/// SQL apply step generated by the webhook reconciler.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct WebhookApplyStep {
    pub name: String,
    pub feature_id: &'static str,
    pub sql: String,
    pub idempotent: bool,
}

impl WebhookApplyStep {
    fn new(
        name: impl Into<String>,
        feature_id: &'static str,
        sql: impl Into<String>,
        idempotent: bool,
    ) -> Self {
        Self {
            name: name.into(),
            feature_id,
            sql: sql.into(),
            idempotent,
        }
    }
}

/// Apply plan composed of `WebhookApplyStep`s in execution order.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct WebhookApplyPlan {
    pub steps: Vec<WebhookApplyStep>,
}

impl WebhookApplyPlan {
    pub fn sql_script(&self) -> String {
        self.steps
            .iter()
            .map(|step| step.sql.trim_end())
            .collect::<Vec<_>>()
            .join("\n")
    }
}

/// Resolved reconcile plan for a `WebhookSpec`. The plan defers to the
/// companion `WebhookRegistrationPlan` for the actual SQL surface so the
/// operator and SQL extension share the same registration contract.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct WebhookReconcilePlan {
    pub webhook_name: String,
    pub table: String,
    pub url: String,
    pub events: Vec<WebhookEvent>,
    pub max_attempts: u32,
    pub backoff: String,
    pub dead_letter_table: Option<String>,
    pub payload_template: Option<String>,
    pub headers_secret_ref: Option<String>,
    pub registration: WebhookSqlPlan,
}

impl WebhookReconcilePlan {
    /// Build a reconcile plan from the spec belonging to the named resource.
    /// `resource_name` is the `metadata.name` of the owning `Webhook` CRD; it
    /// is propagated to the companion `webhook_register` call so observability
    /// reporting can attribute queue rows to the owning CR.
    pub fn from_spec(
        resource_name: &str,
        spec: &WebhookSpec,
    ) -> Result<Self, WebhookReconcileError> {
        let trimmed = resource_name.trim();
        if trimmed.is_empty() {
            return Err(WebhookReconcileError::MissingResourceName);
        }
        spec.validate()?;

        let events = spec.events.clone();
        let companion_events = events
            .iter()
            .map(|event| companion_event(*event))
            .collect::<Vec<_>>();
        let headers = spec
            .headers_secret_ref
            .as_ref()
            .map(|secret_ref| {
                vec![WebhookHeader {
                    name: "Authorization".to_string(),
                    value_secret_ref: secret_ref.clone(),
                }]
            })
            .unwrap_or_default();

        let registration_plan = WebhookRegistrationPlan {
            name: trimmed.to_string(),
            table: spec.table.clone(),
            events: companion_events,
            url: spec.url.clone(),
            headers,
            queue_name: WEBHOOK_QUEUE.to_string(),
            max_retries: spec.retry_policy.max_attempts,
        };
        let registration = registration_plan
            .to_sql_plan()
            .map_err(WebhookReconcileError::from)?;

        Ok(Self {
            webhook_name: trimmed.to_string(),
            table: spec.table.clone(),
            url: spec.url.clone(),
            events,
            max_attempts: spec.retry_policy.max_attempts,
            backoff: spec.retry_policy.backoff.clone(),
            dead_letter_table: spec.retry_policy.dead_letter_table.clone(),
            payload_template: spec.payload_template.clone(),
            headers_secret_ref: spec.headers_secret_ref.clone(),
            registration,
        })
    }

    /// Render the apply plan. The reconciler always invokes the companion
    /// `webhook_register` and trigger installer through `WebhookRegistrationPlan`
    /// so the SQL extension contract owns the trigger fanout.
    pub fn apply_plan(&self) -> WebhookApplyPlan {
        let mut steps = vec![
            WebhookApplyStep::new(
                "ensure_ai_blaise_citus_extension",
                "WH1",
                "CREATE EXTENSION IF NOT EXISTS ai_blaise_citus;".to_string(),
                true,
            ),
            WebhookApplyStep::new(
                "ensure_webhook_metadata_tables",
                "WH1",
                WEBHOOK_METADATA_TABLES_SQL,
                true,
            ),
            WebhookApplyStep::new(
                "register_webhook_and_install_trigger",
                "WH2",
                self.registration.script(),
                true,
            ),
            WebhookApplyStep::new(
                "record_webhook_provenance",
                "WH1",
                record_provenance_sql(self),
                true,
            ),
        ];

        if let Some(template) = &self.payload_template {
            steps.push(WebhookApplyStep::new(
                "record_webhook_payload_template",
                "WH1",
                record_payload_template_sql(&self.webhook_name, template),
                true,
            ));
        }

        if let Some(dlq) = &self.dead_letter_table {
            steps.push(WebhookApplyStep::new(
                "record_webhook_dead_letter_table",
                "WH1",
                record_dlq_sql(&self.webhook_name, dlq),
                true,
            ));
        }

        WebhookApplyPlan { steps }
    }

    pub fn apply_sql_script(&self) -> String {
        self.apply_plan().sql_script()
    }

    /// Teardown plan executed when the CR is deleted.
    pub fn teardown_sql_script(&self) -> String {
        format!(
            "DELETE FROM ai_blaise_webhook_provenance WHERE webhook_name = {name};\nSELECT companion_internal.webhook_unregister({name});",
            name = sql_literal(&self.webhook_name)
        )
    }
}

fn companion_event(event: WebhookEvent) -> CompanionWebhookEvent {
    match event {
        WebhookEvent::Insert => CompanionWebhookEvent::Insert,
        WebhookEvent::Update => CompanionWebhookEvent::Update,
        WebhookEvent::Delete => CompanionWebhookEvent::Delete,
    }
}

fn record_provenance_sql(plan: &WebhookReconcilePlan) -> String {
    let events = plan
        .events
        .iter()
        .map(|event| sql_literal(event_label(*event)))
        .collect::<Vec<_>>()
        .join(", ");
    let headers = plan
        .headers_secret_ref
        .as_deref()
        .map(sql_literal)
        .unwrap_or_else(|| "NULL".to_string());
    let backoff = sql_literal(&plan.backoff);
    let table = sql_literal(&plan.table);
    let url = sql_literal(&plan.url);
    let webhook_name = sql_literal(&plan.webhook_name);
    format!(
        "INSERT INTO ai_blaise_webhook_provenance (webhook_name, table_name, url, events, max_attempts, backoff, headers_secret_ref) VALUES ({webhook_name}, {table}, {url}, ARRAY[{events}], {attempts}, {backoff}, {headers}) ON CONFLICT (webhook_name) DO UPDATE SET table_name = EXCLUDED.table_name, url = EXCLUDED.url, events = EXCLUDED.events, max_attempts = EXCLUDED.max_attempts, backoff = EXCLUDED.backoff, headers_secret_ref = EXCLUDED.headers_secret_ref;",
        attempts = plan.max_attempts,
    )
}

fn record_payload_template_sql(webhook_name: &str, template: &str) -> String {
    format!(
        "INSERT INTO ai_blaise_webhook_payload_templates (webhook_name, payload_template) VALUES ({name}, {template}) ON CONFLICT (webhook_name) DO UPDATE SET payload_template = EXCLUDED.payload_template;",
        name = sql_literal(webhook_name),
        template = sql_literal(template),
    )
}

fn record_dlq_sql(webhook_name: &str, dead_letter_table: &str) -> String {
    format!(
        "INSERT INTO ai_blaise_webhook_dead_letter_targets (webhook_name, dead_letter_table) VALUES ({name}, {dlq}) ON CONFLICT (webhook_name) DO UPDATE SET dead_letter_table = EXCLUDED.dead_letter_table;",
        name = sql_literal(webhook_name),
        dlq = sql_literal(dead_letter_table),
    )
}

fn event_label(event: WebhookEvent) -> &'static str {
    match event {
        WebhookEvent::Insert => "INSERT",
        WebhookEvent::Update => "UPDATE",
        WebhookEvent::Delete => "DELETE",
    }
}

fn sql_literal(value: &str) -> String {
    format!("'{}'", value.replace('\'', "''"))
}

#[derive(Debug, Clone, Eq, PartialEq)]
pub enum WebhookReconcileError {
    InvalidSpec(WebhookSpecError),
    Companion(CompanionWebhookError),
    MissingResourceName,
}

impl fmt::Display for WebhookReconcileError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::InvalidSpec(error) => write!(formatter, "{error}"),
            Self::Companion(error) => write!(formatter, "{error}"),
            Self::MissingResourceName => {
                write!(formatter, "resource_name must not be empty")
            }
        }
    }
}

impl Error for WebhookReconcileError {}

impl From<WebhookSpecError> for WebhookReconcileError {
    fn from(error: WebhookSpecError) -> Self {
        Self::InvalidSpec(error)
    }
}

impl From<CompanionWebhookError> for WebhookReconcileError {
    fn from(error: CompanionWebhookError) -> Self {
        Self::Companion(error)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn full_spec() -> WebhookSpec {
        WebhookSpec {
            table: "public.orders".to_string(),
            events: vec![WebhookEvent::Insert, WebhookEvent::Update],
            url: "https://hooks.example.com/orders".to_string(),
            headers_secret_ref: Some("orders-webhook-headers".to_string()),
            retry_policy: WebhookRetryPolicy {
                max_attempts: 5,
                backoff: "exponential:1s:30s".to_string(),
                dead_letter_table: Some("companion.webhook_dead_letters".to_string()),
            },
            payload_template: Some("{\"table\":\"orders\"}".to_string()),
        }
    }

    fn minimal_spec() -> WebhookSpec {
        WebhookSpec {
            table: "public.events".to_string(),
            events: vec![WebhookEvent::Insert],
            url: "https://hooks.example.com/events".to_string(),
            headers_secret_ref: None,
            retry_policy: WebhookRetryPolicy {
                max_attempts: 3,
                backoff: "fixed:5s".to_string(),
                dead_letter_table: None,
            },
            payload_template: None,
        }
    }

    #[test]
    fn full_plan_includes_payload_and_dlq_steps() {
        let plan =
            WebhookReconcilePlan::from_spec("orders-hook", &full_spec()).expect("valid plan");

        assert_eq!(plan.webhook_name, "orders-hook");
        assert_eq!(plan.max_attempts, 5);
        assert_eq!(plan.events.len(), 2);
        assert_eq!(
            plan.dead_letter_table.as_deref(),
            Some("companion.webhook_dead_letters")
        );

        let apply_plan = plan.apply_plan();
        let names: Vec<&str> = apply_plan
            .steps
            .iter()
            .map(|step| step.name.as_str())
            .collect();
        assert_eq!(
            names,
            vec![
                "ensure_ai_blaise_citus_extension",
                "ensure_webhook_metadata_tables",
                "register_webhook_and_install_trigger",
                "record_webhook_provenance",
                "record_webhook_payload_template",
                "record_webhook_dead_letter_table",
            ]
        );

        let script = plan.apply_sql_script();
        assert!(script.contains("CREATE EXTENSION IF NOT EXISTS ai_blaise_citus;"));
        assert!(script.contains("CREATE TABLE IF NOT EXISTS ai_blaise_webhook_provenance"));
        assert!(script.contains("webhook_register"));
        assert!(script.contains("install_webhook_trigger"));
        assert!(script.contains("ai_blaise_webhook_provenance"));
        assert!(script.contains("ai_blaise_webhook_payload_templates"));
        assert!(script.contains("ai_blaise_webhook_dead_letter_targets"));
        assert!(script.contains("'INSERT'"));
        assert!(script.contains("'UPDATE'"));
    }

    #[test]
    fn minimal_plan_skips_payload_and_dlq_steps() {
        let plan =
            WebhookReconcilePlan::from_spec("events-hook", &minimal_spec()).expect("valid plan");

        let apply_plan = plan.apply_plan();
        assert_eq!(apply_plan.steps.len(), 4);
        let names: Vec<&str> = apply_plan
            .steps
            .iter()
            .map(|step| step.name.as_str())
            .collect();
        assert_eq!(
            names,
            vec![
                "ensure_ai_blaise_citus_extension",
                "ensure_webhook_metadata_tables",
                "register_webhook_and_install_trigger",
                "record_webhook_provenance",
            ]
        );

        let script = plan.apply_sql_script();
        assert!(!script.contains("INSERT INTO ai_blaise_webhook_payload_templates"));
        assert!(!script.contains("INSERT INTO ai_blaise_webhook_dead_letter_targets"));
        assert!(script.contains("NULL"));
    }

    #[test]
    fn teardown_unregisters_webhook_and_provenance() {
        let plan =
            WebhookReconcilePlan::from_spec("orders-hook", &full_spec()).expect("valid plan");
        let teardown = plan.teardown_sql_script();
        assert!(teardown.contains("ai_blaise_webhook_provenance"));
        assert!(teardown.contains("companion_internal.webhook_unregister"));
        assert!(teardown.contains("'orders-hook'"));
    }

    #[test]
    fn missing_resource_name_is_rejected() {
        assert_eq!(
            WebhookReconcilePlan::from_spec("  ", &minimal_spec()),
            Err(WebhookReconcileError::MissingResourceName)
        );
    }

    #[test]
    fn invalid_spec_propagates_validation_error() {
        let mut spec = minimal_spec();
        spec.url = "ftp://nope".to_string();
        assert_eq!(
            WebhookReconcilePlan::from_spec("events-hook", &spec),
            Err(WebhookReconcileError::InvalidSpec(
                WebhookSpecError::InvalidUrl
            ))
        );
    }
}
