apiVersion: v1
kind: Service
metadata:
  name: {{ include "citus-overlay.name" . }}-operator
  labels:
    {{- include "citus-overlay.labels" . | nindent 4 }}
    app.kubernetes.io/component: operator
spec:
  selector:
    app.kubernetes.io/name: {{ include "citus-overlay.name" . }}
    app.kubernetes.io/component: operator
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
