{{- if .Values.operator.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "citus-overlay.name" . }}-operator
  labels:
    {{- include "citus-overlay.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "citus-overlay.name" . }}
      app.kubernetes.io/component: operator
  endpoints:
    - port: metrics
{{- end }}
