apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "citus-overlay.name" . }}-operator
  labels:
    {{- include "citus-overlay.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "citus-overlay.name" . }}-operator
rules:
  - apiGroups: ["ai-blaise.com"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps", "events", "secrets", "services"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "citus-overlay.name" . }}-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "citus-overlay.name" . }}-operator
subjects:
  - kind: ServiceAccount
    name: {{ include "citus-overlay.name" . }}-operator
    namespace: {{ .Release.Namespace }}
