apiVersion: v1
kind: Service
metadata:
  name: {{ include "citus-overlay.name" . }}-pool
  labels:
    {{- include "citus-overlay.labels" . | nindent 4 }}
    app.kubernetes.io/component: pool
spec:
  selector:
    app.kubernetes.io/name: {{ include "citus-overlay.name" . }}
    app.kubernetes.io/component: pool
  ports:
    - name: postgres
      port: {{ .Values.pool.service.port }}
      targetPort: postgres
