{{- if .Values.tools.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "citus-overlay.name" . }}-tools
  labels:
    {{- include "citus-overlay.labels" . | nindent 4 }}
    app.kubernetes.io/component: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "citus-overlay.name" . }}
      app.kubernetes.io/component: tools
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "citus-overlay.name" . }}
        app.kubernetes.io/component: tools
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: citusctl
          image: {{ include "citus-overlay.image" (dict "Values" .Values "repository" .Values.tools.image.repository "tag" .Values.tools.image.tag "digest" .Values.tools.image.digest) }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          command: ["/bin/sleep", "infinity"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          resources:
            {{- toYaml .Values.tools.resources | nindent 12 }}
{{- end }}
