//! Queryable backup branch lifecycle.
//!
//! A queryable backup branch is a PITR restore of a backup archive into a
//! filesystem directory, started as a read-only PostgreSQL instance on a
//! sidecar-controlled port. The branch is the production execution path for
//! `FEATURE: B4` (backup-as-data-source).

// FEATURE: B4

use std::collections::HashMap;
use std::error::Error;
use std::ffi::OsString;
use std::fmt;
use std::fs;
use std::io;
use std::path::PathBuf;
use std::process::{Command, Output, Stdio};

use crate::QueryableBackupBranchPlan;

/// Materializes the read-only PostgreSQL instance for a queryable backup branch
/// on a per-branch data directory.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct QueryableBranchRunner {
    pg_ctl_binary: PathBuf,
    psql_binary: PathBuf,
    branch_root: PathBuf,
    restore_command: String,
}

impl QueryableBranchRunner {
    pub fn new(
        pg_ctl_binary: impl Into<PathBuf>,
        psql_binary: impl Into<PathBuf>,
        branch_root: impl Into<PathBuf>,
    ) -> Self {
        Self {
            pg_ctl_binary: pg_ctl_binary.into(),
            psql_binary: psql_binary.into(),
            branch_root: branch_root.into(),
            restore_command: "wal-g wal-fetch \"%f\" \"%p\"".to_string(),
        }
    }

    pub fn with_restore_command(mut self, restore_command: impl Into<String>) -> Self {
        self.restore_command = restore_command.into();
        self
    }

    /// Data directory under `branch_root` for `plan.branch_name`.
    pub fn data_directory(&self, plan: &QueryableBackupBranchPlan) -> PathBuf {
        self.branch_root.join(&plan.branch_name)
    }

    /// Path to the recovery signal file that puts the restored cluster in
    /// recovery mode at the target time.
    pub fn recovery_signal_path(&self, plan: &QueryableBackupBranchPlan) -> PathBuf {
        self.data_directory(plan).join("recovery.signal")
    }

    /// Path to the per-branch postgresql.auto.conf file that pins the
    /// recovery target time and read-only behavior.
    pub fn auto_conf_path(&self, plan: &QueryableBackupBranchPlan) -> PathBuf {
        self.data_directory(plan).join("postgresql.auto.conf")
    }

    /// Generate the postgresql.auto.conf body for the branch, applying the
    /// recovery target time and the read-only/default_transaction_read_only
    /// settings that B4 requires.
    pub fn auto_conf_body(&self, plan: &QueryableBackupBranchPlan, port: u16) -> String {
        format!(
            "# generated by ai-blaise sidecar/backup for branch {}\n\
             listen_addresses = '127.0.0.1'\n\
             port = {}\n\
             hot_standby = on\n\
             recovery_target_time = '{}'\n\
             recovery_target_action = 'pause'\n\
             restore_command = '{}'\n\
             default_transaction_read_only = on\n\
             archive_mode = off\n",
            plan.branch_name,
            port,
            plan.target_time,
            escape_postgres_conf(&self.restore_command),
        )
    }

    /// Write recovery files into an already restored PostgreSQL data directory.
    pub fn write_recovery_config(
        &self,
        plan: &QueryableBackupBranchPlan,
        port: u16,
    ) -> Result<(), QueryableBranchError> {
        let data_dir = self.data_directory(plan);
        fs::create_dir_all(&data_dir).map_err(QueryableBranchError::Io)?;
        fs::write(self.recovery_signal_path(plan), b"").map_err(QueryableBranchError::Io)?;
        fs::write(self.auto_conf_path(plan), self.auto_conf_body(plan, port))
            .map_err(QueryableBranchError::Io)?;
        Ok(())
    }

    /// Build a `pg_ctl start` command that boots the queryable branch in the
    /// background, writing logs into the branch data directory.
    pub fn start_command(&self, plan: &QueryableBackupBranchPlan) -> Command {
        let data_dir = self.data_directory(plan);
        let log_path = data_dir.join("queryable-branch.log");
        let mut command = Command::new(&self.pg_ctl_binary);
        command.arg("-D");
        command.arg(OsString::from(&data_dir));
        command.arg("-l");
        command.arg(OsString::from(&log_path));
        command.arg("-w");
        command.arg("start");
        command.stdin(Stdio::null());
        command.stdout(Stdio::piped());
        command.stderr(Stdio::piped());
        command
    }

    /// Build a `pg_ctl stop` command that shuts the queryable branch down.
    pub fn stop_command(&self, plan: &QueryableBackupBranchPlan) -> Command {
        let data_dir = self.data_directory(plan);
        let mut command = Command::new(&self.pg_ctl_binary);
        command.arg("-D");
        command.arg(OsString::from(&data_dir));
        command.arg("-m");
        command.arg("fast");
        command.arg("stop");
        command.stdin(Stdio::null());
        command.stdout(Stdio::piped());
        command.stderr(Stdio::piped());
        command
    }

    /// Build a `psql -c` probe that confirms the branch responds to SELECT and
    /// honors the read-only enforcement.
    pub fn read_only_probe_command(&self, _plan: &QueryableBackupBranchPlan, port: u16) -> Command {
        let mut command = Command::new(&self.psql_binary);
        command.arg("-h");
        command.arg("127.0.0.1");
        command.arg("-p");
        command.arg(port.to_string());
        command.arg("-U");
        command.arg("postgres");
        command.arg("-At");
        command.arg("-c");
        command.arg("SELECT 1, current_setting('default_transaction_read_only');");
        command.stdin(Stdio::null());
        command.stdout(Stdio::piped());
        command.stderr(Stdio::piped());
        command
    }

    /// Start the branch and verify the post-start read-only invariant.
    pub fn start_and_verify_read_only(
        &self,
        plan: &QueryableBackupBranchPlan,
        port: u16,
        env: &HashMap<OsString, OsString>,
    ) -> Result<(), QueryableBranchError> {
        let mut start = self.start_command(plan);
        for (key, value) in env {
            start.env(key, value);
        }
        let output = run_command(start).map_err(QueryableBranchError::StartFailed)?;
        if !output.status.success() {
            return Err(QueryableBranchError::StartFailed(output_excerpt(&output)));
        }

        let probe = run_command(self.read_only_probe_command(plan, port))
            .map_err(QueryableBranchError::ReadOnlyViolation)?;
        if !probe.status.success() {
            return Err(QueryableBranchError::ReadOnlyViolation(output_excerpt(
                &probe,
            )));
        }
        let stdout = String::from_utf8_lossy(&probe.stdout).to_ascii_lowercase();
        if !(stdout.contains("|on")
            || stdout.contains("|true")
            || stdout.trim_end().ends_with("on"))
        {
            return Err(QueryableBranchError::ReadOnlyViolation(
                stdout.trim().to_string(),
            ));
        }
        Ok(())
    }
}

/// State of a single queryable branch tracked by the engine.
#[derive(Debug, Clone, Eq, PartialEq)]
pub struct QueryableBranchProcess {
    pub branch_name: String,
    pub data_dir: PathBuf,
    pub port: u16,
    pub target_time: String,
    pub source_archive_uri: String,
}

/// Errors raised when starting or stopping a queryable branch.
#[derive(Debug)]
pub enum QueryableBranchError {
    AlreadyRunning(String),
    Io(io::Error),
    NotFound(String),
    StartFailed(String),
    StopFailed(String),
    ReadOnlyViolation(String),
}

impl fmt::Display for QueryableBranchError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::AlreadyRunning(name) => {
                write!(formatter, "queryable branch {name} already running")
            }
            Self::Io(error) => write!(formatter, "queryable branch filesystem error: {error}"),
            Self::NotFound(name) => write!(formatter, "queryable branch {name} not found"),
            Self::StartFailed(detail) => {
                write!(formatter, "failed to start queryable branch: {detail}")
            }
            Self::StopFailed(detail) => {
                write!(formatter, "failed to stop queryable branch: {detail}")
            }
            Self::ReadOnlyViolation(detail) => {
                write!(formatter, "queryable branch is not read-only: {detail}")
            }
        }
    }
}

impl Error for QueryableBranchError {}

impl PartialEq for QueryableBranchError {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (Self::AlreadyRunning(left), Self::AlreadyRunning(right)) => left == right,
            (Self::Io(left), Self::Io(right)) => left.kind() == right.kind(),
            (Self::NotFound(left), Self::NotFound(right)) => left == right,
            (Self::StartFailed(left), Self::StartFailed(right)) => left == right,
            (Self::StopFailed(left), Self::StopFailed(right)) => left == right,
            (Self::ReadOnlyViolation(left), Self::ReadOnlyViolation(right)) => left == right,
            _ => false,
        }
    }
}

impl Eq for QueryableBranchError {}

fn run_command(mut command: Command) -> Result<Output, String> {
    command.output().map_err(|error| error.to_string())
}

fn output_excerpt(output: &Output) -> String {
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);
    let mut detail = format!(
        "status={:?}; stdout={}; stderr={}",
        output.status.code(),
        stdout,
        stderr
    );
    detail.truncate(512);
    detail
}

fn escape_postgres_conf(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\'', "''")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::canonical_queryable_branch_plan;

    #[test]
    fn data_directory_includes_branch_name() {
        let runner = QueryableBranchRunner::new(
            "/usr/bin/pg_ctl",
            "/usr/bin/psql",
            PathBuf::from("/var/lib/postgresql/branches"),
        );
        let plan = canonical_queryable_branch_plan();
        let data_dir = runner.data_directory(&plan);

        assert!(data_dir.ends_with("prod-at-noon"));
    }

    #[test]
    fn auto_conf_body_pins_recovery_target_and_read_only() {
        let runner = QueryableBranchRunner::new(
            "/usr/bin/pg_ctl",
            "/usr/bin/psql",
            PathBuf::from("/tmp/branches"),
        );
        let plan = canonical_queryable_branch_plan();
        let body = runner.auto_conf_body(&plan, 6543);

        assert!(body.contains("listen_addresses = '127.0.0.1'"));
        assert!(body.contains("port = 6543"));
        assert!(body.contains("recovery_target_time = '2026-05-19T12:00:00Z'"));
        assert!(body.contains("default_transaction_read_only = on"));
        assert!(body.contains("recovery_target_action = 'pause'"));
        assert!(body.contains("restore_command = 'wal-g wal-fetch \"%f\" \"%p\"'"));
    }

    #[test]
    fn write_recovery_config_creates_files() {
        let root = std::env::temp_dir().join(format!("ai-blaise-queryable-{}", std::process::id()));
        let runner = QueryableBranchRunner::new("/usr/bin/pg_ctl", "/usr/bin/psql", &root);
        let plan = canonical_queryable_branch_plan();
        runner
            .write_recovery_config(&plan, 6543)
            .expect("recovery config writes");

        assert!(runner.recovery_signal_path(&plan).exists());
        assert!(runner.auto_conf_path(&plan).exists());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn start_command_uses_pg_ctl_with_data_directory() {
        let runner = QueryableBranchRunner::new(
            "/usr/bin/pg_ctl",
            "/usr/bin/psql",
            PathBuf::from("/tmp/branches"),
        );
        let plan = canonical_queryable_branch_plan();
        let command = runner.start_command(&plan);
        let program = command.get_program().to_string_lossy().into_owned();
        let args: Vec<String> = command
            .get_args()
            .map(|arg| arg.to_string_lossy().into_owned())
            .collect();

        assert_eq!(program, "/usr/bin/pg_ctl");
        assert!(args.contains(&"-D".to_string()));
        assert!(args.contains(&"start".to_string()));
        assert!(args.contains(&"-w".to_string()));
        assert!(args.iter().any(|arg| arg.ends_with("prod-at-noon")));
    }

    #[test]
    fn stop_command_uses_fast_mode() {
        let runner = QueryableBranchRunner::new(
            "/usr/bin/pg_ctl",
            "/usr/bin/psql",
            PathBuf::from("/tmp/branches"),
        );
        let plan = canonical_queryable_branch_plan();
        let command = runner.stop_command(&plan);
        let args: Vec<String> = command
            .get_args()
            .map(|arg| arg.to_string_lossy().into_owned())
            .collect();

        assert!(args.contains(&"fast".to_string()));
        assert!(args.contains(&"stop".to_string()));
    }

    #[test]
    fn read_only_probe_targets_127_0_0_1_and_pinned_port() {
        let runner = QueryableBranchRunner::new(
            "/usr/bin/pg_ctl",
            "/usr/bin/psql",
            PathBuf::from("/tmp/branches"),
        );
        let plan = canonical_queryable_branch_plan();
        let command = runner.read_only_probe_command(&plan, 6543);
        let program = command.get_program().to_string_lossy().into_owned();
        let args: Vec<String> = command
            .get_args()
            .map(|arg| arg.to_string_lossy().into_owned())
            .collect();

        assert_eq!(program, "/usr/bin/psql");
        let port_index = args
            .iter()
            .position(|arg| arg == "-p")
            .expect("-p argument");
        assert_eq!(args.get(port_index + 1), Some(&"6543".to_string()));
        assert!(args
            .iter()
            .any(|arg| arg.contains("default_transaction_read_only")));
    }
}
