apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-blaise-citus
spec:
  project: default
  source:
    repoURL: https://github.com/ai-blaise/citus
    targetRevision: main
    path: deploy/k8s/helm/citus-overlay
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-blaise-citus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
